name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # runs-on: macos-12
    runs-on: [self-hosted, macOS]

    env:
      XCODE_COMMON_BUILD_ARGS: -project Source/iOS/App/DolphiniOS.xcodeproj -derivedDataPath "${{ github.workspace }}/build-Xcode" DOL_PBID_ORGANIZATION_IDENTIFIER="me.oatmealdome" DOL_BUILD_SOURCE="development" CODE_SIGNING_ALLOWED="NO" CODE_SIGNING_REQUIRED="NO"
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      # - name: Set Xcode Version
      #   run: sudo xcode-select -s /Applications/Xcode_14.2.app

      # - name: Install Build Utilities
      #   run: |
      #     brew install cmake ninja bartycrouch
      #     /usr/bin/python3 -m pip install polib

      - name: Build Application
        run: |
          xcodebuild -configuration "Release (Non-Jailbroken)" -scheme "DiOS (NJB)" ${{ env.XCODE_COMMON_BUILD_ARGS }}
          xcodebuild -configuration "Release (Jailbroken)" -scheme "DiOS (JB)" ${{ env.XCODE_COMMON_BUILD_ARGS }}
